### ISSUE TITLE
Not Working With Firmware v14.3 

### ISSUE THREAD

**Issue by Syd3Suess** [bitfocus/companion-module-epson-businesspj#4]
jumped from v11.1 to v14.3 and this no longer works

**Comment by Syd3Suess** [comment]
@josephdadams

**Comment by josephdadams** [comment]
Guess you’ll be jumping back to v11.1

**Comment by Syd3Suess** [comment]
or you could make a patch to your code that asks for a web control password. the issue is the Web Controller asks you to change the password from admin to do anything

**Comment by josephdadams** [comment]
Not my code. This is not my module. It’s an open source project, so feel free to submit a pull request!
